#Configuración de POS - Frontend
#Sat Jul 04 21:32:41 BOT 2026
app.modo=SERVIDOR
app.modulo.cocina=true
app.negocio.logo=default.png
app.negocio.nombre=Attizos
app.servidor.ip=localhost
loggin.level.root=INFO
